apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "myapp.fullname" . }}-http-check
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  args:
    - name: canary-hash
  metrics:
    - name: pod-readiness
      interval: 15s
      count: 3
      failureLimit: 1
      successCondition: result[0] >= 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(
              kube_pod_status_ready{
                namespace="{{ .Release.Namespace }}",
                condition="true"
              } * on(pod) group_left()
              kube_pod_labels{
                namespace="{{ .Release.Namespace }}",
                label_app_kubernetes_io_name="{{ include "myapp.name" . }}",
                label_rollouts_pod_template_hash="{{`{{args.canary-hash}}`}}"
              }
            )
